apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "docker.io/redis:{{ .Values.redisCache.version }}"
        command:
          - redis-server
          - "/config/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /data
          name: redis-volume
        - mountPath: /config
          name: config
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
            claimName: redis-pvc
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf